seed : 42
cuda : True
star : ''
root_dir : '/mnt/nvme0n1p5/projects/UDA-ADL/data'
batch_size : 2
patch_size : 32
input_nc : 1
output_nc : 1
ngf : 64
ndf : 64
lr : 0.001
beta1: 0.5
threads : 4
num_classes: 1